---
- name: Multiple user wala
  hosts: all
  become: true

  tasks:
      - name: add a list of users
        user: name='{{ item }}' state=present
        with_items:
          - kapil
          - aniket
          - nikhil

